{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-test.serviceAccountName" . }}
  namespace: docs
  labels:
    {{- include "nginx-test.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    app: nginx
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

