apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: docs
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /docs
    - uri:
        regex: ^.*\.(ico|png|jpg|css|js|img|jpeg|map)$
    route:
    - destination:
        host: nginx-service
        port:
          number: 8080
